# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consum',
            name='consum_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consumtype',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
